version: '3.8'

services:
  postgres:
    image: postgres
    container_name: cl-postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - '5435:5432'
    restart: always
    volumes:
      - dbdata-chainlink:/var/lib/postgresql/data


volumes:
  dbdata-chainlink:
    driver: local
